# Generated by Django 6.0.6 on 2026-07-08 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='reported_by',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=5)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date_reported', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='FoundItem',
        ),
        migrations.DeleteModel(
            name='LostItem',
        ),
    ]
